# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 21:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_jobs', to='login_app.User')),
                ('grabbed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doing_jobs', to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='jobs_in_category',
            field=models.ManyToManyField(related_name='categories', to='helper_app.Job'),
        ),
    ]
