# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 23:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0002_auto_20181218_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='jobs_in_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='helper_app.Job'),
        ),
    ]
