# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-18 23:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0003_auto_20181218_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='grabbed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doing_jobs', to='login_app.User'),
        ),
    ]
