# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-19 00:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('helper_app', '0004_auto_20181218_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='grabbed_by',
        ),
        migrations.AddField(
            model_name='job',
            name='grabbed_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='doing_jobs', to='login_app.User'),
        ),
    ]
