# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-19 02:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helper_app', '0005_auto_20181219_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='jobs_in_category',
        ),
        migrations.AddField(
            model_name='job',
            name='categories',
            field=models.CharField(default=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
